### ISSUE TITLE
1.12.2 1.17.0 Patch Bugs

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#145] opened 2020-01-06 16:56 UTC
Issue Description:

Pokemob stand/sit and follow icons have disappeared (the buttons remain)

Ash Pikachu has been removed (unsure if intended)

Eevee has been added to the starters list (this looks like a remnant from another pack the Eevee is also invisible)

Some moves in the Galar set have spelling errors to match the move (also assuming that there are some that haven't been made yet)

The new portal is failing to generate the new dimension correctly 2 crash reports will follow (if this is due to forced generation of portals my apologies for raising an alarm)

This list is incomplete and more thorough testing will follow but congrats on getting a patch out so fast and thorough for such a small group of people.

Affected Versions:
Pokecube AIO: 1.17.0
Minecraft: 1.12.2
Forge: 14.23.5.2847

[crash-2020-01-07_03.01.51-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4026977/crash-2020-01-07_03.01.51-server.txt)
[crash-2020-01-07_03.09.17-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4026978/crash-2020-01-07_03.09.17-server.txt)

**Comment by prjohns** [comment] 2020-01-06 18:40
the pikachu thing was intended, that capability was supposed to be done a different way, not requiring a pokedex entry (there is a way to make specific individual mobs use custom models, without needing full pokedex specification)
eevee starter was not, I will remove that, that probably got accidentally merged in from resource stuff.

If you can specify exactly which moves have the errors, that will make it easier to fix

there are a couple other bugs related to the new portals I need to look into, they otherwise worked well on dev mode, thanks for the crash reports, they should help.

**Closed** 2020-03-22 03:06 UTC
Labels: Bug - Code
