### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by schkrisz1** [Pokecube-Development/Pokecube-Issues-and-Wiki#1083] opened 2022-11-05 18:45 UTC
Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

**Comment by schkrisz1** [comment] 2022-11-05 18:45
Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

**Comment by Thutmose** [comment] 2022-11-05 19:47
duplicate of #1082

**Closed as completed by Thutmose** 2022-11-05 19:47 UTC
Labels: Unconfirmed

**Comment by schkrisz1** [comment] 2022-11-06 09:05
Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

**Comment by Thutmose** [comment] 2022-11-06 17:24
I will close the other issue as well, as it appears that you are a bot.

**Comment by schkrisz1** [comment] 2022-11-06 17:30
I'm not a bot, BUT the problem STILL EXISTS despite closing this thread. But as I can see, he is not even willing to pay attention to solving the problem.

Thanks for the BIG nothing!

**Comment by Thutmose** [comment] 2022-11-06 17:35
oh, then why did you not provide the information requested in #1082?

**Comment by Thutmose** [comment] 2022-11-06 17:36
when opening the issue, it gives a template to fill out, please fill that out in a new issue.

**Comment by schkrisz1** [comment] 2022-11-06 17:48
I wrote a new #1084.
