### ISSUE TITLE
Client Entity Animation Crash

### ISSUE THREAD

**Issue by Darkfiend009** [Pokecube-Development/Pokecube-Issues-and-Wiki#890] opened 2022-01-29 14:42 UTC
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

Client side crash while exploring the world.
Crash Report: https://pastebin.com/3LKqeQJs

#### What happens:
Client crashes. Unsure the specific entity that caused the crash.

#### What you expected to happen:
Nothing

#### Steps to reproduce:

Hard to reproduce as it wasn't a specific action of the player
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.15.0
- Minecraft: 1.18.1
- Forge: 39.0.63

**Comment by Thutmose** [comment] 2022-01-30 00:39
duplicate of #877 reply to comments via that issue instead, if you have a reliable way to replicate this, please give instructions

**Closed as completed by Thutmose** 2022-01-30 00:39 UTC
Labels: duplicate
