### ISSUE TITLE
pokemobs sent out in different dimesions breaks them

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#423] opened 2020-05-30 17:49 UTC
#### Issue Description:
pokemobs sent out in different dimesions become unusable 

#### What happens:
the pokemob does not move from the spot it was sent out at and cant sit or use moves 

#### What you expected to happen:
to work fine without being broken/stuck in one spot when going to different dimensions 

#### Steps to reproduce:

1.send out a pokemob from the overworld in ultra space, nether, or end and recall it
2.send it back out and notice it wont move from the spot it was sent out and acts like its frozen in place
3.go back to the world it was caught and send it out and notice it works fine
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.7.2
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment] 2020-05-30 21:04
I suspect this is a duplicate of #419

**Comment by monkeycrazie** [comment] 2020-05-30 21:19
It is but it adds a better explanation

**Comment by Thutmose** [comment] 2020-05-30 21:38
yes, which is why I just marked it without closing it

**Closed** 2020-05-31 01:23 UTC
Labels: 1.14.x, 1.15.2, Bug - Code, Fixed, duplicate
