### ISSUE TITLE
Chisel breaks when pokecube and a few mods combined. It only seems to break if all these mods are together.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Pokecube-Development/Pokecube-Issues-and-Wiki#74] opened 2019-05-23 20:14 UTC
https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/issues/16#issuecomment-495110126

https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/issues/16

https://github.com/Chisel-Team/Chisel/issues/776

All information you need is in these areas.

**Comment by Thutmose** [comment] 2019-05-23 21:11
for 776, I need to see what is supposed to happen without the mod, and with it as a comparison.

**Comment by P3rf3ctXZer0** [comment] 2019-05-23 21:56
Chisel is a mod which basically allows many type of different textures with existing vanilla blocks. Here are some examples.
![2019-05-23 16_54_42-Window](https://user-images.githubusercontent.com/10351221/58289331-aee1e500-7d7b-11e9-8ceb-9cd120fd6ad5.jpg)

**Comment by P3rf3ctXZer0** [comment] 2019-05-23 21:56
![2019-05-23 16_55_34-Window](https://user-images.githubusercontent.com/10351221/58289355-c15c1e80-7d7b-11e9-9b6a-a17eeb4a7201.jpg)

**Comment by Thutmose** [comment] 2019-05-23 22:04
and show the blocks placed in the world with and without pokecube?

**Comment by P3rf3ctXZer0** [comment] 2019-05-23 23:27
Wait why? They look like blocks with flat decorative textures. What are you trying to understand? When they glitch they look like single color blocks with no texture of any kind.

**Comment by P3rf3ctXZer0** [comment] 2019-05-23 23:36
![2019-05-23 18_31_20-Windows Media Player](https://user-images.githubusercontent.com/10351221/58293033-7943f880-7d89-11e9-9586-a003065d3ab7.jpg)

Of course when I wanted to show case it failing I flockking can't despite how much I tried. I tested using this release https://minecraft.curseforge.com/projects/pokecube-aoi/files/2715056

**Comment by Thutmose** [comment] 2019-05-24 00:55
could it be something going wrong in the JEI display then? ie see if they are still messed up there.

**Comment by AlluringEmerald** [comment] 2019-05-30 01:49
![working](https://user-images.githubusercontent.com/48238895/58602524-e86e9080-8252-11e9-8137-83cfb4759137.png)
![broken](https://user-images.githubusercontent.com/48238895/58602525-e86e9080-8252-11e9-9eb9-f3f880dca74f.png)
I can confirm this bug, I reproduced it too. It seems to mainly take effect when creating a new world or entering a dimension not yet generated, though it seems to happen randomly too. It works fine after restarting Minecraft, but as I said, it sometimes randomly happens in a already-generated world.

**Comment by P3rf3ctXZer0** [comment] 2019-06-04 12:44
10 Min video. You can watch each step I took before it broke.
https://www.youtube.com/watch?v=Sn05bcj4qB0&feature=youtu.be

[debug.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/3252398/debug.log)
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/3252399/latest.log)
[NBTEditpqb.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/3252400/NBTEditpqb.log)

![2019-06-04 02_38_26-Window](https://user-images.githubusercontent.com/10351221/58880016-8bcd0480-869c-11e9-8838-ca361a9199ea.jpg)

**Comment by P3rf3ctXZer0** [comment] 2019-06-05 09:29
Interesting just before the error takes place this time it had a unique crash ...

https://gist.github.com/P3rf3ctXZer0/939db50409edbfc12b22f0fa043817aa

**Comment by Thutmose** [comment] 2019-06-05 12:38
that is an unrelated error, that is fixed in 1.15.8, that was caused by a fix for pokeplayers...

**Comment by P3rf3ctXZer0** [comment] 2019-06-05 16:24
![2019-06-05 11_09_27-Window](https://user-images.githubusercontent.com/10351221/58972536-62d36f00-8783-11e9-9590-992fb90b73b0.jpg)
![2019-06-05_11 10 32](https://user-images.githubusercontent.com/10351221/58972562-71218b00-8783-11e9-8d62-30b6e0c8ed2c.png)
![2019-06-05_11 10 37](https://user-images.githubusercontent.com/10351221/58972563-71218b00-8783-11e9-9692-ca6f79f807f2.png)
![2019-06-05_11 10 39](https://user-images.githubusercontent.com/10351221/58972564-71218b00-8783-11e9-8dc0-f482cb1e0ce6.png)
![Uploading 2019-06-05_11.10.52.png…]()

A curse of two mods. 
https://youtu.be/1eixZWu4sIk

@Thutmose watch the video you can skip to 14 but you should watch the whole thing since you keep ask me to do arbitrary and useless things.


A curse of two mods. 
https://youtu.be/1eixZWu4sIk

@Thutmose watch the video you can skip to 14 but you should watch the whole thing since you keep ask me to do arbitrary and useless things.

**Comment by Thutmose** [comment] 2019-06-06 00:00
This is an interaction between wearables and chisel, not related to pokecube, so I will close this issue, discussions should continue on https://github.com/Chisel-Team/Chisel/issues/776

**Closed by Thutmose** 2019-06-06 00:00 UTC
Labels: Compatibility Issue
